# Generated by Django 2.2.5 on 2022-03-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0003_measurement_patient_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='content',
        ),
        migrations.AddField(
            model_name='measurement',
            name='diastolic_blood_pressure',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='measurement',
            name='glucometer',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='measurement',
            name='oximeter',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='measurement',
            name='pulse',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='measurement',
            name='systolic_blood_pressure',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(default=-1),
        ),
        migrations.AddField(
            model_name='measurement',
            name='weight',
            field=models.FloatField(default=-1),
        ),
    ]
