# Generated by Django 2.2.5 on 2022-03-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0004_auto_20220314_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='diastolic_blood_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='glucometer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='oximeter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='patient_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='pulse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='systolic_blood_pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
