# Generated by Django 2.2.5 on 2022-03-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0002_auto_20220314_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='patient_id',
            field=models.IntegerField(default=-1),
        ),
    ]
