# Generated by Django 2.2.5 on 2022-03-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0005_auto_20220314_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='patient_id',
            field=models.IntegerField(default=-1),
        ),
    ]
