# Generated by Django 2.2.5 on 2022-03-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0006_auto_20220314_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
