# Generated by Django 2.2.5 on 2022-03-15 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0007_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device_api.Patient'),
        ),
    ]
